version: '3.4'
services:
  db:
    image: timescale/timescaledb:2.1.0-pg13
    container_name: eth_listener_pq
    restart: always
    volumes:
      - ./data/volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: eth_listener
      POSTGRES_USER: listener
      POSTGRES_PASSWORD: listener_AA9944
